[package]
name = "bacon"
version = "0.1.0"
authors = ["aspera-non-spernit <g.s.d>"]
edition = "2018"

[dependencies]
bigint = "4.4.1"
bincode = "1.1.2"
chacha = "0.3.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "*"
rand = "0.6.5"
