[package]
name = "bacon"
version = "0.1.0"
authors = ["aspera-non-spernit <g.s.d>"]
edition = "2018"

[dependencies]
bincode = "1.1.2"
persy = "0.4.0"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
rand = "0.6.5"
