[package]
name = "bacon"
version = "0.1.0"
authors = ["aspera-non-spernit <g.s.d>"]
edition = "2018"

[dependencies]
bincode = "*"
persy = "0.4.0"
serde = "*"
serde_derive = "*"
serde_json = "*"
rand = "*"
